version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise
    restart: always
    ports:
      - "3000:3000"
  web-1:
    build: 
      context: .
    restart: always
    ports: 
      - "6080:80"
  web-2:
    build: 
      context: .
    restart: always
    ports: 
      - "7080:80"
  web-3:
    build: 
      context: .
    restart: always
    ports: 
      - "8080:80"
