version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: password
  pgadmin4:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "53080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "password"
    restart: always
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-enterprise
    restart: always
    ports:
      - "3000:3000"
  web-1:
    build: 
      context: .
    restart: always
    ports: 
      - "6080:80"
    environment:
      - "ConnectionStrings__Hangfire=Host=host.docker.internal;Port=5432;Database=postgres;Username=postgres;Password=password"
  web-2:
    build: 
      context: .
    restart: always
    ports: 
      - "7080:80"
    environment:
      - "ConnectionStrings__Hangfire=Host=host.docker.internal;Port=5432;Database=postgres;Username=postgres;Password=password"
  web-3:
    build: 
      context: .
    restart: always
    ports: 
      - "8080:80"
    environment:
      - "ConnectionStrings__Hangfire=Host=host.docker.internal;Port=5432;Database=postgres;Username=postgres;Password=password"
